# Generated by Django 5.1.1 on 2024-11-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username'], 'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
    ]
